# Generated by Django 3.1.4 on 2020-12-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noxcrux_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horcrux',
            old_name='data',
            new_name='horcrux',
        ),
        migrations.AddField(
            model_name='horcrux',
            name='site',
            field=models.CharField(default='https://localhost', max_length=255),
            preserve_default=False,
        ),
    ]
