# Generated by Django 3.1.4 on 2020-12-29 18:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noxcrux_api', '0004_horcrux_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horcrux',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='horcrux',
            unique_together={('name', 'owner')},
        ),
    ]
