# Generated by Django 3.1.4 on 2021-01-05 20:58
# Edited on 2022-04-21 to delete django-cryptography dependency

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noxcrux_api', '0005_auto_20201229_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horcrux',
            name='horcrux',
            field=models.CharField(max_length=255),
        ),
    ]
