# Generated by Django 3.1.4 on 2021-01-05 20:58

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('noxcrux_api', '0005_auto_20201229_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horcrux',
            name='horcrux',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255)),
        ),
    ]
