# Generated by Django 3.1.4 on 2021-01-16 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noxcrux_api', '0008_auto_20210116_1829'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Generator',
        ),
    ]
