# Generated by Django 3.1.4 on 2021-01-31 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noxcrux_api', '0011_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='friend',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friend',
            name='user',
            field=models.OneToOneField(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('user', 'friend')},
        ),
        migrations.RemoveField(
            model_name='friend',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='to_user',
        ),
    ]
