# Generated by Django 3.1.4 on 2021-01-31 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noxcrux_api', '0012_auto_20210131_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='from_user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friend',
            name='to_user',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('from_user', 'to_user')},
        ),
        migrations.RemoveField(
            model_name='friend',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user',
        ),
    ]
