# Generated by Django 3.2.4 on 2021-08-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noxcrux_api', '0019_auto_20210813_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
