# Generated by Django 3.2.12 on 2022-04-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noxcrux_api', '0024_alter_userkeyscontainer_iv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horcrux',
            name='horcrux',
            field=models.CharField(max_length=255),
        ),
    ]
