# Generated by Django 3.2.12 on 2022-04-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noxcrux_api', '0025_alter_horcrux_horcrux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horcrux',
            name='horcrux',
            field=models.CharField(max_length=8192),
        ),
    ]
