# Generated by Django 3.2.13 on 2022-04-30 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noxcrux_api', '0026_alter_horcrux_horcrux'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userkeyscontainer',
            old_name='private_key',
            new_name='protected_key',
        ),
    ]
