# Generated by Django 3.2.13 on 2022-08-05 08:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noxcrux_api', '0028_auto_20220612_1439'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sharedhorcrux',
            unique_together={('horcrux', 'grantee')},
        ),
    ]
