version: "3.9"

services:

  noxcrux_db:
    image: postgres:13
    container_name: noxcrux_db
    restart: always
    expose:
      - "5432"
    networks:
      - noxcrux_db_net
    environment:
      POSTGRES_DB: noxcrux
      POSTGRES_USER: noxcrux
      POSTGRES_PASSWORD_FILE: /run/secrets/noxcrux_db_passwd
    volumes:
      - db:/var/lib/postgresql/data
    secrets:
      - noxcrux_db_passwd
    user: postgres:postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U noxcrux"]
      interval: 10s
      timeout: 5s
      retries: 10
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges

  noxcrux_web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: noxcrux:web
    container_name: noxcrux_web
    restart: always
    expose:
      - "8000"
    networks:
      - noxcrux_db_net
      - noxcrux_web_net
    environment:
      DEBUG: 0
      REGISTRATION_OPEN: 1
      DB_HOST: noxcrux_db
      DB_PORT: "5432"
      DB_NAME: noxcrux
      DB_USER: noxcrux
      ALLOWED_HOSTS: "localhost,127.0.0.1,0.0.0.0"
      CORS_ALLOW_ALL_ORIGINS: 0
      CORS_ALLOWED_ORIGINS: "https://localhost,https://127.0.0.1,https://0.0.0.0"
    volumes:
      - static_files:/usr/src/app/static/
    secrets:
      - noxcrux_db_passwd
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    depends_on:
      noxcrux_db:
        condition: service_healthy

  noxcrux_nginx:
    build:
      context: ../
      dockerfile: docker/Dockerfile.nginx
    image: noxcrux:nginx
    container_name: noxcrux_nginx
    restart: always
    ports:
      - "80:8080"
      - "443:44380"
    networks:
      - noxcrux_web_net
    volumes:
      - static_files:/srv/static/
    secrets:
      - source: certificate
        target: /srv/certificates/fullchain.pem
      - source: private_key
        target: /srv/certificates/privkey.pem
      - source: dh_params
        target: /srv/certificates/dhparams.pem
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges

volumes:

  db:
    name: noxcrux_db

  static_files:
    name: noxcrux_static_files
    driver_opts:
      type: tmpfs
      device: tmpfs

secrets:

  noxcrux_db_passwd:
    file: ./secrets/noxcrux_db_passwd.txt

  certificate:
    file: ./ssl/fullchain.pem

  private_key:
    file: ./ssl/privkey.pem

  dh_params:
    file: ./ssl/dhparams.pem

networks:

  noxcrux_db_net:
    name: noxcrux_db_net
    ipam:
      driver: default
      config:
        - subnet: "172.26.0.72/29"
    driver_opts:
      com.docker.network.bridge.name: dbr-noxcrux_db

  noxcrux_web_net:
    name: noxcrux_web_net
    ipam:
      driver: default
      config:
        - subnet: "172.26.0.80/29"
    driver_opts:
      com.docker.network.bridge.name: dbr-noxcrux_web
